config/routes.rb
Rails.application.routes.draw do

  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, :scope => :ingredient

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [:new, :create, :destroy]

  def new
    @dose = Dose.new
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.doses.last.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <br />

  <%= f.submit %>
<% end %>

app/views/cocktails/index.html.erb
<div class="container text-center">

  <% @cocktails.each do |cocktail| %>
   <ul style="list-style: none;">
    <li> <%= cocktail.name %> <li>
  </ul>
  <% end %>

</div>

app/views/cocktails/new.html.erb
<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="container text-center">

    <h1> <%= @cocktail.name %> </h1>

  <h2>Doses</h2>
  <ul class="text-center" style="list-style: none; list-style-position: outside">
    <% @cocktail.doses.each do |dose| %>
    <li> ID: <%= dose.id %> </li>
    <li> Description: <%= dose.description %> </li>
    <li> Ingredient: <%= Ingredient.find(dose.ingredient_id).name %> </li>
    <% end %>
  </ul>


<p> <%= link_to "Add a new cocktail", new_cocktail_path(@cocktail), class: "btn btn-primary" %> </p>

<p> <%= link_to "Show all cocktails", cocktails_path, class: "btn btn-primary" %> </p>

<p> <%= link_to "Add a new dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %> </p>

<p> <%= link_to "Delete a dose", cocktail_dose_path(@cocktail), method: :delete, class: "btn btn-primary" %> </p>


</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1> Dose for <%= @cocktail.name %> </h1>

<h2> Please select an ingredient from the list below </h2>


<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient%>
  <%= f.submit "Add this dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>